---
# Install Java Debian Package

- name: Add Repository if specified
  apt_repository: repo='{{ _oracle_jdk.apt_repo.repo_line }}'
  when: _oracle_jdk is defined and _oracle_jdk.apt_repo is defined and _oracle_jdk.apt_repo.repo_line is defined and _oracle_jdk.apt_repo.repo_line != ""

- name: Auto-Accept Oracle Licensing Terms
  debconf: name="oracle-java8-installer" setting="shared/accepted-oracle-license-v1-1" vtype="select" value="true"

- name: Install Java 8 JDK
  apt:
    state: latest
    name:
      - oracle-java8-installer
      - oracle-java8-unlimited-jce-policy

- name: "Set security setting for DNS cache ttl"
  lineinfile:
    path: "{{ _oracle_jdk.install_dir }}/jre/lib/security/java.security"
    regexp: '^(.*)networkaddress.cache.ttl=(.*)$'
    line: "networkaddress.cache.ttl={{ _oracle_jdk.security.dns_cache_ttl }}"

- name: "Set security setting for DNS cache negative ttl"
  lineinfile:
    path: "{{ _oracle_jdk.install_dir }}/jre/lib/security/java.security"
    regexp: '^(.*)networkaddress.cache.negative.ttl=(.*)$'
    line: "networkaddress.cache.negative.ttl={{ _oracle_jdk.security.dns_cache_negative_ttl }}"
