---
# Install Java Debian Package

- name: Add Repository if specified
  apt_repository: repo='{{ _oracle_jdk.apt_repo.repo_line }}'
  when: _oracle_jdk is defined and _oracle_jdk.apt_repo is defined and _oracle_jdk.apt_repo.repo_line is defined and _oracle_jdk.apt_repo.repo_line != ""

- name: Auto-Accept Oracle Licensing Terms
  debconf: name="oracle-java8-installer" setting="shared/accepted-oracle-license-v1-1" vtype="select" value="true"

- name: Install Java 8 JDK
  apt: name="{{ item }}" state=latest
  with_items:
    - oracle-java8-installer
    - oracle-java8-unlimited-jce-policy

