---
# Install Java via PPA

- name: Add webupd8team PPA
  apt_repository: repo='ppa:webupd8team/java'

- name: Auto-Accept Oracle Licensing Terms
  debconf: name="oracle-java8-installer" setting="shared/accepted-oracle-license-v1-1" vtype="select" value="true"

- name: Install Java 8 JDK
  apt: name="{{ item }}" state=latest
  with_items:
    - oracle-java8-installer
    - oracle-java8-unlimited-jce-policy

